# encoding: UTF-8

require 'factory_girl'

Reason.delete_all
r1 = FactoryGirl.create(:reason, :label => 'Corruption')
r2 = FactoryGirl.create(:reason, :label => 'Collusion')
r3 = FactoryGirl.create(:reason, :label => 'Manque de transparence')
r4 = FactoryGirl.create(:reason, :label => 'Manque de vision')
r5 = FactoryGirl.create(:reason, :label => 'Mauvaise gestion')

Example.delete_all
FactoryGirl.create(:example, :headline => "Charest délait de deux ans la commission d'enquête Charbonneau.", :excerpt => "le premier ministre Jean Charest et son ministre de la Sécurité publique d'alors, Jacques Dupuis, rejettent sans relâche l'idée d'une commission d'enquête. «Laissons les policiers travailler», martèle à l'Assemblée nationale le ministre Dupuis. «Une commission d'enquête si nécessaire, mais pas nécessairement une commission d'enquête», insiste de son côté M. Charest.", :link => "http://www.ledevoir.com/politique/quebec/339456/le-revirement-de-l-annee-2011-la-commission-d-enquete", :published_at => Date.civil(2012, 1, 3), :reasons => [r1, r3], :approved => true)

FactoryGirl.create(:example, :headline => "Le gouvernement tien au secret les négotiations de libre-échange avec l'Union Européenne.", :excerpt => "Ce qui est en cause dans ces négociations, c’est moins l’idée du libre-échange que la manière de négocier sans débat public, comme si seuls de grands technocrates pouvaient comprendre les enjeux en cause. On dit qu’une élection est l’occasion pour un gouvernement de rendre des comptes. Quels comptes rendra donc Jean Charest sur cette négociation avec l’Union européenne ? Aucun, car il prétendra être tenu au secret.", :link => "http://www.ledevoir.com/politique/quebec/354647/libre-echange-le-secret", :reasons => [r2,r3], :published_at => Date.civil(2012, 7, 16), :approved => true)

FactoryGirl.create(:example, :headline => "Le gouvernement vend à rabais les droits d'exploitation pétrolière.", :excerpt => "Actuellement, Québec touche environ 1 million de dollars pour les 10 millions d'hectares sous permis. Mais les commissaires du Bureau d'audiences publiques sur l'environnement (BAPE) ont clairement souligné dans leur rapport que le gouvernement devrait recevoir beaucoup plus: «En se référant au prix moyen de 500 $/hectare de l'Alberta, le Québec aurait pu percevoir environ 5 milliards de dollars pour les 10 millions d'hectares sous permis.» Pour en tirer des milliards à verser au trésor public, il aurait fallu procéder par une attribution aux enchères, comme cela se fait en Colombie-Britannique, en Alberta et en Saskatchewan. Dans ces provinces, «le marché détermine la valeur de chaque parcelle selon les bénéfices attendus de son exploitation», ont noté les commissaires du BAPE.", :link => "http://www.ledevoir.com/economie/actualites-economiques/321058/exploration-et-exploitation-gaziere-et-petroliere-quebec-revise-les-droits-et-permis", :approved => true, :reasons => [r3,r4], :published_at => Date.civil(2012, 4, 14))

FactoryGirl.create(:example, :headline => "Au lieu d'entrer en dialogue, le gouvernement fait du marketing pour promouvoir son point de vue sur la hausse des droits de scolarité.", :excerpt => "«Ce que recommandait le comité, c'était de faire la promotion de l'importance de l'éducation et du programme prêts et bourses. Pas d'utiliser ça à des fins partisanes!» rétorque Léo Bureau-Blouin, président de la FECQ.\n\nSelon lui, cette campagne montre que la mobilisation étudiante inquiète le gouvernement. «Ils utilisent la crédibilité des associations étudiantes en achetant leurs acronymes pour mousser leur campagne. C'est une stratégie douteuse», dit-il.", :link => "http://www.lapresse.ca/actualites/quebec-canada/education/201111/11/01-4466986-quebec-achete-greve-etudiante-sur-google.php", :approved => true, :reasons => [r4,r5], :published_at => Date.civil(2011, 11, 11))

FactoryGirl.create(:example, :headline => "Le gouvernement refuse le dialogue et se cache derrière une loi spéciale qui bafoue les chartes des droits du Québec.", :excerpt => "La toute récente loi 78 est sans doute l'une des lois spéciales québécoises les plus (sinon la plus) lourdement attentatoires aux droits fondamentaux protégés par les chartes canadienne et québécoise. Que l'on analyse le texte sous l'angle de la liberté d'association et du droit d'agir collectivement, de la liberté de conscience, de la liberté d'expression ou du droit de manifester pacifiquement, presque tous les articles de cette nouvelle loi soulèvent, à leur face même, de sérieux doutes quant à leur compatibilité avec les chartes applicables au Québec. Mais au-delà de ces graves enjeux, une chose nous paraît encore plus préoccupante, et c'est la manière que semble avoir choisie le gouvernement québécois pour tenter de justifier l'adoption de cette loi.", :link => "http://www.lapresse.ca/le-soleil/opinions/points-de-vue/201205/23/01-4527774-loi-78-un-odieux-detournement-de-lesprit-des-chartes.php", :approved => true, :reasons => [r4,r5], :published_at => Date.civil(2012, 5, 24))

FactoryGirl.create(:example, :headline => "Charest est en collusion avec l'industrie de la construction.", :excerpt => "Fruit d'un an et demi d'enquête sur le terrain, le rapport confirme l'implication du crime organisé dans l'industrie de la construction et parle d'une « banalisation du gonflement des estimations par certaines firmes de génie-conseil et des dépassements de coût par certains entrepreneurs ».\n\nSelon l'Unité anticollusion, des ingénieurs de firmes de génie-conseil, mais aussi des employés du ministère, favorisent des entrepreneurs en leur fournissant des informations privilégiées. Ils leur indiqueraient, par exemple, qu'un contrat où l'on prévoit 1000 chargements de terre contaminée n'en nécessitera véritablement qu'une centaine.", :link => "http://www.radio-canada.ca/nouvelles/National/2011/09/14/003-unite-anticollusion-rapport.shtml", :approved => true, :reasons => [r4,r5], :published_at => Date.civil(2011, 9, 17))

FactoryGirl.create(:example, :headline => "Charest laisse les pressions politiques influencer la nomination des juges de la Cour du Québec.", :excerpt => "À son arrivée au pouvoir, Jean Charest a modifié la procédure de nomination des juges en permettant au Conseil des ministres d'avoir accès à la liste des candidats. Le ministre de la Justice, qui gardait cette liste pour lui auparavant, est maintenant exposé aux pressions politiques de ses collègues.", :link => "http://www.ledevoir.com/politique/quebec/286990/nomination-des-juges-charest-a-change-la-donne", :approved => true, :reasons => [r4,r5], :published_at => Date.civil(2010, 4, 15))

FactoryGirl.create(:example, :headline => "Le gouvernement exploite la procédure du bâillon pour passer ses lois.", :excerpt => "Doit-on s'alarmer de voir le gouvernement Charest imposer le bâillon pour permettre l'adoption de ses projets de loi? On pourrait se contenter de hausser les épaules tellement le recours à cette mesure est chose quasi routinière à Québec. Pourtant, il y a lieu de s'inquiéter, car, encore une fois, les projets les plus importants du gouvernement seront adoptés à toute vapeur, sans examen et débat en profondeur.", :link => "http://www.ledevoir.com/non-classe/43006/plus-ca-change", :approved => true, :reasons => [r4,r5], :published_at => Date.civil(2003, 12, 16))

Admin.delete_all
FactoryGirl.create(:admin, :email => 'cawel00@charest-la-honte.com', :password => "youhavelostcontrol")
FactoryGirl.create(:admin, :email => 'matthieutc@charest-la-honte.com', :password => "youhavelostcontrol")
