# encoding: UTF-8

require 'factory_girl'

Reason.delete_all
r1 = FactoryGirl.create(:reason, :label => 'Corruption')
r2 = FactoryGirl.create(:reason, :label => 'Collusion')
r3 = FactoryGirl.create(:reason, :label => 'Manque de transparence')
r4 = FactoryGirl.create(:reason, :label => 'Non-écoute de la population')
r5 = FactoryGirl.create(:reason, :label => 'Mauvaise gestion')
r6 = FactoryGirl.create(:reason, :label => 'Anti-démocratique')

Example.delete_all
FactoryGirl.create(:example, :headline => "Jean Charest a affirmé qu'il ne tiendra pas compte du rapport de l'Unité permanente anticorruption", :excerpt => "Lors d'une conférence de presse convoquée pour vanter tous les gestes posés par son gouvernement afin de contrer la corruption et la collusion (création de l'Unité permanente anticorruption et adoption de lois et de règlements, par exemple), Jean Charest réduit le rapport Duchesneau, qu'il n'a pas lu, à des allégations. Il est hors de question pour lui de commenter le rapport car, affirme-t-il, «le politique ne va pas mettre le nez là-dedans». Du coup, il met le feu aux poudres chez ses adversaires, qui se déchaînent et en appellent à la révolte populaire.", :link => "http://www.ledevoir.com/politique/quebec/339456/le-revirement-de-l-annee-2011-la-commission-d-enquete", :published_at => Date.civil(2012, 1, 3), :reasons => [r1, r2, r3, r4], :approved => true)

FactoryGirl.create(:example, :headline => "Malgré la grogne populaire, les scandales à répétition, le gouvernement Charest refusera pendant plus de 2 ans l'idée d'une commission d'enquête sur l'industrie de la construction", :excerpt => "Les mois suivants apportent leur lot de scandales, d'octrois de contrats et d'allégations de financement douteux des partis politiques. La grogne populaire augmente, le monde politique nage en pleine tourmente, mais le gouvernement libéral ne cède pas.", :link => "http://www.ledevoir.com/politique/quebec/339456/le-revirement-de-l-annee-2011-la-commission-d-enquete", :published_at => Date.civil(2012, 1, 3), :reasons => [r1, r2, r4], :approved => true)

FactoryGirl.create(:example, :headline => "Le gouvernement tient secret les négociations de libre-échange avec l'Union Européenne", :excerpt => "Ce qui est en cause dans ces négociations, c’est moins l’idée du libre-échange que la manière de négocier sans débat public, comme si seuls de grands technocrates pouvaient comprendre les enjeux en cause. On dit qu’une élection est l’occasion pour un gouvernement de rendre des comptes. Quels comptes rendra donc Jean Charest sur cette négociation avec l’Union européenne ? Aucun, car il prétendra être tenu au secret.", :link => "http://www.ledevoir.com/politique/quebec/354647/libre-echange-le-secret", :reasons => [r3, r4], :published_at => Date.civil(2012, 7, 16), :approved => true)

FactoryGirl.create(:example, :headline => "Le gouvernement vend à rabais les droits d'exploitation pétrolière", :excerpt => "Actuellement, Québec touche environ 1 million de dollars pour les 10 millions d'hectares sous permis. Mais les commissaires du Bureau d'audiences publiques sur l'environnement (BAPE) ont clairement souligné dans leur rapport que le gouvernement devrait recevoir beaucoup plus: «En se référant au prix moyen de 500 $/hectare de l'Alberta, le Québec aurait pu percevoir environ 5 milliards de dollars pour les 10 millions d'hectares sous permis.» Pour en tirer des milliards à verser au trésor public, il aurait fallu procéder par une attribution aux enchères, comme cela se fait en Colombie-Britannique, en Alberta et en Saskatchewan. Dans ces provinces, «le marché détermine la valeur de chaque parcelle selon les bénéfices attendus de son exploitation», ont noté les commissaires du BAPE.", :link => "http://www.ledevoir.com/economie/actualites-economiques/321058/exploration-et-exploitation-gaziere-et-petroliere-quebec-revise-les-droits-et-permis", :approved => true, :reasons => [r2, r5], :published_at => Date.civil(2012, 4, 14))

FactoryGirl.create(:example, :headline => "Au lieu d'entrer en dialogue, le gouvernement fait du marketing pour promouvoir son point de vue sur la hausse des droits de scolarité", :excerpt => "«Ce que recommandait le comité, c'était de faire la promotion de l'importance de l'éducation et du programme prêts et bourses. Pas d'utiliser ça à des fins partisanes!» rétorque Léo Bureau-Blouin, président de la FECQ.\n\nSelon lui, cette campagne montre que la mobilisation étudiante inquiète le gouvernement. «Ils utilisent la crédibilité des associations étudiantes en achetant leurs acronymes pour mousser leur campagne. C'est une stratégie douteuse», dit-il.", :link => "http://www.lapresse.ca/actualites/quebec-canada/education/201111/11/01-4466986-quebec-achete-greve-etudiante-sur-google.php", :approved => true, :reasons => [r5], :published_at => Date.civil(2011, 11, 11))

FactoryGirl.create(:example, :headline => "Le gouvernement refuse le dialogue et se cache derrière une loi spéciale qui bafoue les chartes des droits du Québec", :excerpt => "La toute récente loi 78 est sans doute l'une des lois spéciales québécoises les plus (sinon la plus) lourdement attentatoires aux droits fondamentaux protégés par les chartes canadienne et québécoise. Que l'on analyse le texte sous l'angle de la liberté d'association et du droit d'agir collectivement, de la liberté de conscience, de la liberté d'expression ou du droit de manifester pacifiquement, presque tous les articles de cette nouvelle loi soulèvent, à leur face même, de sérieux doutes quant à leur compatibilité avec les chartes applicables au Québec. Mais au-delà de ces graves enjeux, une chose nous paraît encore plus préoccupante, et c'est la manière que semble avoir choisie le gouvernement québécois pour tenter de justifier l'adoption de cette loi.", :link => "http://www.lapresse.ca/le-soleil/opinions/points-de-vue/201205/23/01-4527774-loi-78-un-odieux-detournement-de-lesprit-des-chartes.php", :approved => true, :reasons => [r4, r5], :published_at => Date.civil(2012, 5, 24))

FactoryGirl.create(:example, :headline => "Selon le rapport de l'UPAC, il y a collusion entre le gouvernement Charest et l'industrie de la construction", :excerpt => "Selon l'Unité anticollusion, des ingénieurs de firmes de génie-conseil, mais aussi des employés du ministère, favorisent des entrepreneurs en leur fournissant des informations privilégiées. Ils leur indiqueraient, par exemple, qu'un contrat où l'on prévoit 1000 chargements de terre contaminée n'en nécessitera véritablement qu'une centaine.", :link => "http://www.radio-canada.ca/nouvelles/National/2011/09/14/003-unite-anticollusion-rapport.shtml", :approved => true, :reasons => [r2,r3], :published_at => Date.civil(2011, 9, 17))

FactoryGirl.create(:example, :headline => "Charest veut avoir droit de regard sur la nomination des juges de la Cour du Québec", :excerpt => "À son arrivée au pouvoir, Jean Charest a modifié la procédure de nomination des juges en permettant au Conseil des ministres d'avoir accès à la liste des candidats. Le ministre de la Justice, qui gardait cette liste pour lui auparavant, est maintenant exposé aux pressions politiques de ses collègues.", :link => "http://www.ledevoir.com/politique/quebec/286990/nomination-des-juges-charest-a-change-la-donne", :approved => true, :reasons => [r5, r6], :published_at => Date.civil(2010, 4, 15))

FactoryGirl.create(:example, :headline => "Le gouvernement exploite la procédure du bâillon pour passer plusieurs lois importantes", :excerpt => "Doit-on s'alarmer de voir le gouvernement Charest imposer le bâillon pour permettre l'adoption de ses projets de loi? On pourrait se contenter de hausser les épaules tellement le recours à cette mesure est chose quasi routinière à Québec. Pourtant, il y a lieu de s'inquiéter, car, encore une fois, les projets les plus importants du gouvernement seront adoptés à toute vapeur, sans examen et débat en profondeur.", :link => "http://www.ledevoir.com/non-classe/43006/plus-ca-change", :approved => true, :reasons => [r6], :published_at => Date.civil(2003, 12, 16))

FactoryGirl.create(:example, :headline => "Jean Charest choisit de faire campagne durant les vacances d'été", :excerpt => "L'essentiel de la campagne se déroulera dans une période où la politique ne préoccupe guère la population, une perspective rassurante pour un gouvernement qui n'a pas envie de faire campagne sur un bilan de neuf ans.", :link => "http://www.lapresse.ca/actualites/quebec-canada/politique-quebecoise/201207/10/01-4542539-elections-aux-urnes-le-4-septembre.php", :approved => true, :reasons => [r6], :published_at => Date.civil(2012, 07, 11))

FactoryGirl.create(:example, :headline => "Les Libéraux ont fermé la division Pétrole et gaz d'Hydro-Québec et ont cédé au secteur privé l'ensemble des permis d'exploration gazière et pétrolière", :excerpt => "Avant de céder au secteur privé l'ensemble des permis d'exploration gazière et pétrolière qu'elle possédait, Hydro-Québec prévoyait investir plus de 330 millions de dollars entre 2002 et 2010 afin d'évaluer le potentiel en énergies fossiles du sous-sol québécois et du golfe du Saint-Laurent. Les libéraux ont toutefois mis fin aux activités de la division Pétrole et gaz de la Société d'État, un choix qui revient à avoir bradé les ressources en hydrocarbures du Québec, dénonce l'opposition.", :link => "http://www.ledevoir.com/politique/quebec/316842/hydro-voulait-continuer-a-explorer", :approved => true, :reasons => [r5], :published_at => Date.civil(2011, 02, 15))

Admin.delete_all
raise "specify admin password as an environment variable" if ENV['ADMIN_PASSWORD'].blank? 
FactoryGirl.create(:admin, :email => 'cawel00@charest-les-faits.com', :password => ENV['ADMIN_PASSWORD'])
FactoryGirl.create(:admin, :email => 'matthieutc@charest-les-faits.com', :password => ENV['ADMIN_PASSWORD'])

puts "DB is now seeded."
